/* Drop Table */

DROP TABLE PLAGE;
DROP TABLE RESERVATION;
DROP TABLE SALLE;
DROP TABLE SORTIE;
DROP TABLE MEMBRE;
DROP TABLE ENTREE;
DROP TABLE AUTORISATION;
DROP TABLE PERIODE_ACCES;
DROP TABLE ALARME_ACCES;
DROP TABLE AFFECTATION;
DROP TABLE ADMINISTRATEUR;
DROP TABLE ACCES;
DROP TABLE PERSONNE;
DROP TABLE PAPIER_IDENTITE;
DROP TABLE PLAGE_HORAIRE;
DROP TABLE PLAGE_SEMAINE;
DROP TABLE POINT_ACCES;
DROP TABLE BATIMENT;
DROP TABLE JOUR_FERIE;
DROP TABLE GROUPE_BATIMENTS;
DROP TABLE GROUPE;
DROP TABLE BADGE;
DROP TABLE ALARME;