CREATE OR REPLACE TRIGGER TR_autorisationGroupe
AFTER UPDATE OR INSERT ON AUTORISATION
DECLARE
	
	metasemaineDebut integer;
	metasemaineFin integer;
	metahoraireDebut date;
	metahoraireFin date;
	semaineDebut integer;
	semaineFin integer;
	horaireDebut date;
	horaireFin date;
	id_groupeBat integer :=-1;
	requete varchar(200);
BEGIN
	FOR autorisation IN (SELECT * FROM AUTORISATION)
	LOOP
	
		IF (id_groupeBat <> autorisation.id_groupebat) THEN
			id_groupeBat := autorisation.id_groupebat;
			requete := 'SELECT PS.SEMAINE_DEBUT FROM AUTORISATION A,PLAGE P,PLAGE_SEMAINE PS,GROUPE_BATIMENTS GB, GROUPE G WHERE A.ID_GROUPEBAT= ' || id_groupeBat || ' and A.ID_GROUPEBAT=GB.ID_GROUPEBAT and A.ID_GROUPEPERS=G.ID_GROUPEPERS and GB.NOMGROUPEBAT=G.NOMGROUPEPERS and A.LIBELLE_PLAGE_ACCES = P.LIBELLE_PLAGE_ACCES and P.LIBELLE_PLAGE_SEMAINE = PS.LIBELLE_PLAGE_SEMAINE' ;
			EXECUTE IMMEDIATE (requete) into metasemaineDebut;
			requete := 'SELECT PS.SEMAINE_FIN FROM AUTORISATION A,PLAGE P,PLAGE_SEMAINE PS,GROUPE_BATIMENTS GB, GROUPE G WHERE A.ID_GROUPEBAT=' || id_groupeBat || ' and A.ID_GROUPEBAT=GB.ID_GROUPEBAT and A.ID_GROUPEPERS=G.ID_GROUPEPERS and GB.NOMGROUPEBAT=G.NOMGROUPEPERS and A.LIBELLE_PLAGE_ACCES = P.LIBELLE_PLAGE_ACCES and P.LIBELLE_PLAGE_SEMAINE = PS.LIBELLE_PLAGE_SEMAINE' ;
			EXECUTE IMMEDIATE (requete) into metasemaineFin;
			requete := 'SELECT PH.HORAIRE_DEBUT FROM AUTORISATION A,PLAGE P, PERIODE_ACCES PA, PLAGE_HORAIRE PH,GROUPE_BATIMENTS GB, GROUPE G WHERE A.ID_GROUPEBAT=' || id_groupeBat || 'and A.ID_GROUPEBAT=GB.ID_GROUPEBAT and A.ID_GROUPEPERS=G.ID_GROUPEPERS and GB.NOMGROUPEBAT=G.NOMGROUPEPERS and A.LIBELLE_PLAGE_ACCES = PA.LIBELLE_PLAGE_ACCES and PA.LIBELLE_PLAGE_HORAIRE= PH.LIBELLE_PLAGE_HORAIRE' ;
			EXECUTE IMMEDIATE (requete) into metahoraireDebut;
			requete := 'SELECT PH.HORAIRE_FIN FROM AUTORISATION A,PLAGE P, PERIODE_ACCES PA, PLAGE_HORAIRE PH,GROUPE_BATIMENTS GB, GROUPE G WHERE A.ID_GROUPEBAT=' || id_groupeBat || ' and A.ID_GROUPEBAT=GB.ID_GROUPEBAT and A.ID_GROUPEPERS=G.ID_GROUPEPERS and GB.NOMGROUPEBAT=G.NOMGROUPEPERS and A.LIBELLE_PLAGE_ACCES = PA.LIBELLE_PLAGE_ACCES and PA.LIBELLE_PLAGE_HORAIRE= PH.LIBELLE_PLAGE_HORAIRE' ;
			EXECUTE IMMEDIATE (requete) into metahoraireFin;
		END IF;
		
		requete := 'SELECT PS.SEMAINE_DEBUT FROM AUTORISATION A,PLAGE P,PLAGE_SEMAINE PS WHERE A.ID_GROUPEPERS =' || autorisation.ID_GROUPEPERS || ' and A.LIBELLE_PLAGE_ACCES = P.LIBELLE_PLAGE_ACCES and P.LIBELLE_PLAGE_SEMAINE = PS.LIBELLE_PLAGE_SEMAINE';
		EXECUTE IMMEDIATE (requete) into semaineDebut;
		requete := 'SELECT PS.SEMAINE_FIN FROM AUTORISATION A,PLAGE P,PLAGE_SEMAINE PS WHERE A.ID_GROUPEPERS =' || autorisation.ID_GROUPEPERS || ' and A.LIBELLE_PLAGE_ACCES = P.LIBELLE_PLAGE_ACCES and P.LIBELLE_PLAGE_SEMAINE = PS.LIBELLE_PLAGE_SEMAINE';
		EXECUTE IMMEDIATE (requete) into semaineFin;
		requete := 'SELECT PH.HORAIRE_DEBUT FROM AUTORISATION A,PLAGE P, PERIODE_ACCES PA, PLAGE_HORAIRE PH WHERE A.ID_GROUPEPERS =' || autorisation.ID_GROUPEPERS || ' and A.LIBELLE_PLAGE_ACCES = PA.LIBELLE_PLAGE_ACCES and PA.LIBELLE_PLAGE_HORAIRE= PH.LIBELLE_PLAGE_HORAIRE';
		EXECUTE IMMEDIATE (requete) into horaireDebut;
		requete := 'SELECT PH.HORAIRE_FIN FROM AUTORISATION A,PLAGE P, PERIODE_ACCES PA, PLAGE_HORAIRE PH WHERE A.ID_GROUPEPERS =' || autorisation.ID_GROUPEPERS || ' and A.LIBELLE_PLAGE_ACCES = PA.LIBELLE_PLAGE_ACCES and PA.LIBELLE_PLAGE_HORAIRE= PH.LIBELLE_PLAGE_HORAIRE';
		EXECUTE IMMEDIATE (requete) into horaireFin;
		
		IF (semaineDebut < metasemaineDebut or semaineFin > metasemaineFin or horaireDebut < metahoraireDebut or horaireFin > metahoraireFin) THEN
			RAISE_APPLICATION_ERROR(-20002,'Les autorisations du groupe ' || autorisation.ID_GROUPEPERS || ' ne sont pas incluses dans les autorisations generales du groupe de batiment ' || autorisation.ID_GROUPEBAT);
		END IF;
	END LOOP;

			

		
	
END;
/